apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rails-template-stimulus-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  tls:
    - hosts:
        - example.com
      secretName: rails-template-stimulus-tls
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rails-template-stimulus-web-svc
                port:
                  number: 80