apiVersion: batch/v1
kind: Job
metadata:
  name: astemplate-migration
spec:
  template:
    spec:
      imagePullSecrets:
        - name: docker-hub-key
      containers:
        - name: migration-app
          image: # TODO Paste your image url
          imagePullPolicy: Always
          command: ["bundle", "exec", "rake", "db:migrate"]
          env:
          - name: RAILS_ENV
            value: "production"
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: astemplate-secrets
                key: astemplate-master-key
      restartPolicy: Never