apiVersion: batch/v1
kind: Job
metadata:
  name: rails-template-stimulus-migration
spec:
  template:
    spec:
      containers:
        - name: migration-app
          image: # TODO Paste your image url
          command: ["bundle", "exec", "rake", "db:migrate"]
          env:
          - name: RAILS_ENV
            value: "production"
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails-template-stimulus-secrets
                key: rails-template-stimulus-master-key
      restartPolicy: Never