default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_template_stimulus_development

test:
  <<: *default
  database: rails_template_stimulus_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || Rails.application.credentials.dig(:production, :database_url) %>